news/urls.py
from django.urls import path
from .views import NewsArticleView
from . import views

app_name = 'news'
urlpatterns = [
    path('all/', views.news_all, name='all'),
    path('<slug:link>/', NewsArticleView.as_view(), name="article_page")
]

undergroups/urls.py
from django.urls import path

from .views import Undergroup_detail_view, Undergroup_list_view, suggest_sjiraffenvers_view, faq_view, faq_item_create
from .views import sjiraffenvers_landing_view, SjiraffenversListView, StudenterSangListView, StudenterSangDetailView
from .views import faq_item_edit, faq_category_create

app_name = 'undergroups'
urlpatterns = [
    path('sjiraffenversgenerator-og-sang/', sjiraffenvers_landing_view, name='sjiraffenvers_main'),
    path('alle-sjiraffenvers/', SjiraffenversListView.as_view(), name='sjiraffenvers_list'),
    path('song/<int:pk>/', StudenterSangDetailView.as_view(), name='song_detail'),
    path('suggest-sjiraffenvers/', suggest_sjiraffenvers_view, name='suggest_sjiraffenvers'),
    path('faq/', faq_view, name='faq'),
    path('andre-sanger/', StudenterSangListView.as_view(), name='song_list'),
    path('', Undergroup_list_view.as_view(), name="undergroup_list"),
    path('<slug:slug>/', Undergroup_detail_view.as_view(), name="undergroup_page"),
    path('faq/add/', faq_item_create, name='faq_item_create'),
    path('faq/edit/<int:pk>/', faq_item_edit, name='faq_item_edit'),
    path('faq/category/add/', faq_category_create, name='faq_category_create'),
]

undergroups/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify
from tinymce.models import HTMLField


class Undergroup(models.Model):
    name = models.CharField(max_length=200)
    short_info = models.TextField(max_length=10000, blank=True)
    history = models.TextField(max_length=30000, blank=True)
    long_info = models.TextField(max_length=30000, blank=True)
    slug = models.SlugField(unique=True, null=False)
    logo = models.ImageField(upload_to='undergroups/logos', null=True, blank=True)
    cover_image = models.ImageField(upload_to='undergroups/coverimages', null=True, blank=True)

    class Meta():
        verbose_name_plural = "Undergrupper"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('undergroups:undergroup_page', kwargs={'slug': self.slug})

    def save(self, *args, **kwars):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwars)


class Sjiraffenvers(models.Model):
    title = models.CharField(max_length=255)  # Title of the verse
    line1 = models.CharField(max_length=255)  # First line of the verse
    line2 = models.CharField(max_length=255)  # Second line of the verse
    line3 = models.CharField(max_length=255)  # Third line of the verse
    line4 = models.CharField(max_length=255)  # Fourth line of the verse
    creator = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)  # Timestamp for creation

    def __str__(self):
        return self.title  # Display the title in admin

    def full_verse(self):
        # Combines all the lines into a full verse
        return "\n".join([self.line1, self.line2, self.line3, self.line4])

    class Meta:
        verbose_name_plural = "Sjiraffenvers"  # Correct plural spelling


class StudenterSang(models.Model):
    title = models.CharField(max_length=255)
    lyrics = models.TextField()
    melody = models.CharField(max_length=255, default="Ukjent", null=True)

    CREATOR_CHOICES = (
        ('Sanger av Tåkeluren', 'Sanger av Tåkeluren'),
        ('Annen Studentersang', 'Annen Studentersang'),
        ('Sanger av MiT', 'Sanger av MiT'),
        ('RUKA-sang', 'RUKA-sang'),
    )

    creator = models.CharField(max_length=50, choices=CREATOR_CHOICES, default='Tåkeluren')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('undergroups:song_detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name_plural = "Andre Sanger"  # Correct plural spelling


class FAQCategory(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class FAQFile(models.Model):
    file = models.FileField(upload_to='faq_files/')

    def __str__(self):
        return f"{self.file.name}"


class FAQItem(models.Model):
    category = models.ForeignKey(FAQCategory, related_name='faq_items', on_delete=models.CASCADE)
    subcategory = models.CharField(max_length=200)
    answer = HTMLField()
    files = models.ManyToManyField(FAQFile, related_name='faq_items', blank=True)

    def __str__(self):
        return self.subcategory

undergroups/forms.py
from django import forms
from .models import Sjiraffenvers, FAQItem, FAQCategory, FAQFile


class SuggestSjiraffenversForm(forms.ModelForm):
    class Meta:
        model = Sjiraffenvers
        fields = ['title', 'line1', 'line2', 'line3', 'line4', 'creator']
        labels = {
            'title': 'Tittel',
            'line1': 'Linje 1',
            'line2': 'Linje 2',
            'line3': 'Linje 3',
            'line4': 'Linje 4',
            'creator': 'Forfatter',
        }


class FAQItemForm(forms.ModelForm):
    category = forms.ModelChoiceField(
        queryset=FAQCategory.objects.all(),
        empty_label="Choose Category",
        label='Kategori',
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    subcategory = forms.CharField(
        label='Tittel',
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    answer = forms.CharField(
        label='Innhold',
        required=False,
        widget=forms.Textarea(attrs={'class': 'form-control tinymce'})
    )

    class Meta:
        model = FAQItem
        fields = ['category', 'subcategory', 'answer']

    def save(self, commit=True):
        instance = super(FAQItemForm, self).save(commit=False)

        if commit:
            instance.save()
            self.save_m2m()  # Save the many-to-many data for the form.

            # Handle the file upload here
            files = self.files.getlist('files')  # 'files' is the name of the form field for file uploads
            for f in files:
                faq_file = FAQFile(file=f)
                faq_file.save()
                instance.files.add(faq_file)  # Add the file to the many-to-many relationship

        return instance


class FAQCategoryForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Skriv inn ny kategori'}
    ), label='Kategori')

    class Meta:
        model = FAQCategory
        fields = ['name']

undergroups/views.py
import random
from itertools import groupby
from operator import attrgetter

from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import DetailView, ListView

from .forms import SuggestSjiraffenversForm, FAQItemForm, FAQCategoryForm
from .models import Undergroup, Sjiraffenvers, StudenterSang, FAQCategory, FAQItem, FAQFile


class Undergroup_list_view(ListView):
    model = Undergroup
    context_object_name = 'group_list'
    template_name = 'undergroups/group_list.html'
    ordering = ["name"]


class Undergroup_detail_view(DetailView):
    model = Undergroup
    context_object_name = 'group'
    template_name = 'undergroups/base_groups.html'


@login_required
def sjiraffenvers_landing_view(request):
    verses = Sjiraffenvers.objects.all()
    random_verse = random.choice(verses) if verses.exists() else None
    return render(request, 'undergroups/tåkeluren/tåkeluren_main.html', {'random_verse': random_verse})


class SjiraffenversListView(LoginRequiredMixin, ListView):
    model = Sjiraffenvers
    context_object_name = 'verses'
    template_name = 'undergroups/tåkeluren/sjiraffenvers_list.html'
    ordering = ['title']  # Replace 'title' with the actual field name you want to sort by


class StudenterSangListView(LoginRequiredMixin, ListView):
    model = StudenterSang
    context_object_name = 'grouped_songs'
    template_name = 'undergroups/tåkeluren/song_list.html'

    def sort_grouped_songs(self, grouped_songs):
        creator_order = {key: i for i, (key, _) in enumerate(StudenterSang.CREATOR_CHOICES)}
        return sorted(grouped_songs, key=lambda x: creator_order.get(x[0], float('inf')))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        creators = groupby(self.get_queryset(), attrgetter('creator'))
        grouped_songs = [(creator, list(songs)) for creator, songs in creators]
        context['grouped_songs'] = self.sort_grouped_songs(grouped_songs)
        return context


class StudenterSangDetailView(LoginRequiredMixin, DetailView):
    model = StudenterSang
    template_name = 'undergroups/tåkeluren/song_detail.html'
    context_object_name = 'song'


@login_required
def suggest_sjiraffenvers_view(request):
    if request.method == 'POST':
        form = SuggestSjiraffenversForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('undergroups:sjiraffenvers_main')  # Redirect to a success page or the main page
    else:
        form = SuggestSjiraffenversForm()

    return render(request, 'undergroups/tåkeluren/suggest_sjiraffenvers.html', {'form': form})


def faq_view(request):
    faq_categories = FAQCategory.objects.all()
    return render(request, 'undergroups/faq/faq.html', {'faq_categories': faq_categories})


def is_styret_user(user):
    if user.groups.filter(name='Styret').exists():
        return True
    else:
        raise PermissionDenied


@login_required
@user_passes_test(is_styret_user)
def faq_item_create(request):
    if request.method == 'POST':
        form = FAQItemForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('undergroups:faq')
    else:
        form = FAQItemForm()

    return render(request, 'undergroups/faq/faq_item_form.html', {
        'form': form
    })


@login_required
@user_passes_test(is_styret_user)
def faq_item_edit(request, pk):
    faq_item = get_object_or_404(FAQItem, pk=pk)
    form = FAQItemForm(instance=faq_item)
    existing_files = faq_item.files.all()

    if request.method == 'POST':
        form = FAQItemForm(request.POST, request.FILES, instance=faq_item)
        if form.is_valid():
            form.save()

            # Handle deletion of files marked for deletion
            delete_files = request.POST.getlist('delete_files')  # 'delete_files' is the name of the checkbox input
            for file_id in delete_files:
                try:
                    file_to_delete = FAQFile.objects.get(id=file_id)
                    file_to_delete.delete()  # Delete the file from database and filesystem
                except FAQFile.DoesNotExist:
                    pass  # If file doesn't exist, do nothing

            return redirect('undergroups:faq')
    else:
        form = FAQItemForm(instance=faq_item)

    return render(request, 'undergroups/faq/faq_item_edit.html', {
        'form': form,
        'existing_files': existing_files,
        'faq_item': faq_item,
    })


@login_required
@user_passes_test(is_styret_user)
def faq_category_create(request):
    if request.method == 'POST':
        category_form = FAQCategoryForm(request.POST)
        if category_form.is_valid():
            category_form.save()
            return redirect('undergroups:faq_item_create')  # Redirect back to FAQ item creation
    else:
        category_form = FAQCategoryForm()

    return render(request, 'undergroups/faq/faq_category_form.html', {'category_form': category_form})

templates/undergroups/tåkeluren/sjiraffenvers_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Alle Sjiraffenvers{% endblock %}

{% block content %}


<div class="container custom-container text-center mt-3 bg-white shadow rounded">
    <h1 class="mb-2">Sjiraffenvers</h1>
    <div class="row mb-4 mt-3">
        <div class="col-md-3 mx-auto">
            <a class="btn btn-default w-100" href="{% url 'undergroups:sjiraffenvers_main' %}">Tilbake til Sjiraffenvers-generator</a>
        </div>
    </div>
    <hr>
    <div class="white-box">
        {% for verse in verses %}
            <h2>{{ verse.title }}</h2>
            <p>{{ verse.full_verse | linebreaksbr }}</p>
            <p><b>Forfatter: </b> {{ verse.creator }}</p>
            <hr>
        {% endfor %}
    </div>
    <p class="text-white">Jeg sliter med å kode</p>
</div>
{% endblock %}

templates/undergroups/tåkeluren/song_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ song.title }}{% endblock %}

{% block content %}
<div class="container mt-4 mb-4 bg-white shadow rounded">
    <!-- This row and col-md-8 will center the column in the middle for medium to large screens -->
    <div class="row justify-content-center">
        <div class="col-md-5">
            <h1 class="mb-4">{{ song.title }}</h1>
            <div class="row">
                <div class="col-12"> <!-- This will take full width on small screens -->
                    <a class="btn btn-default w-100" href="{% url 'undergroups:song_list' %}">Tilbake til sangliste</a>
                </div>
            </div>
            {% if song.melody %}
            <p class="mt-4"><i><strong>Melodi:</strong> {{ song.melody }}</i></p>
            {% endif %}
            <!-- Preformatted text block for lyrics aligned to the left -->
            <pre style="white-space: pre-wrap; text-align: left;">{{ song.lyrics }}</pre>
        </div>
    </div>
</div>
{% endblock %}    <p class="text-white">Jeg sliter med å kode</p>

templates/undergroups/tåkeluren/song_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Sanger{% endblock %}

{% block app_css %}
<link rel="stylesheet" href={% static "/undergroups/css/tåkeluren.css" %}>{% endblock %}

{% block content %}
<div class="container text-center mt-3 mb-3 bg-white shadow rounded">
    <h1 class="mb-4">Kjente og Gamle Sanger</h1>
    <div class="row mb-3">
        <div class="col-md-3 mx-auto">
            <a class="btn btn-default w-100" href="{% url 'undergroups:sjiraffenvers_main' %}">Tilbake til Sjiraffenvers-generator</a>
        </div>
    </div>
    <p>Liste med både tradisjonelle studentersanger og eldre sanger fra Tåkeluren-hefte.</p>
    <div style="background-color: white;">
    {% for creator, group_songs in grouped_songs %}
        {% with group_songs|first as first_song %}
            <h2 class="mt-5 mb-2">{{ first_song.get_creator_display }}</h2>
        {% endwith %}
        {% for song in group_songs %}
            <div class="list-group-item">
                <a class="text-dark" href="{{ song.get_absolute_url }}">{{ song.title }}</a>
            </div>
        {% endfor %}
    {% endfor %}
    <p class="text-white">Jeg sliter med å kode</p>
    </div>
</div>
{% endblock %}

templates/undergroups/tåkeluren/suggest_sjiraffenvers.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Nytt Sjiraffenvers{% endblock %}

{% block content %}
<div class="container text-center mt-4 mb-4 bg-white shadow rounded">
    <h1 class="mb-4">Nytt Sjiraffenvers</h1>
    <div class="row mb-4">
        <div class="col-md-3 mt-1 mx-auto">
            <a class="btn btn-default w-100" href="{% url 'undergroups:sjiraffenvers_main' %}">Tilbake til Sjiraffenvers-generator</a>
        </div>
    </div>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
            </div>
        {% endfor %}
        <div class="row">
            <div class="col-md-3 mx-auto"> <!-- mx-auto for auto margins on the sides -->
                <button type="submit" class="btn btn-default mb-3 mt-3">Send inn</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

templates/undergroups/tåkeluren/tåkeluren_main.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Sjiraffenvers-Generator{% endblock %}

{% block content %}
<div class="container text-center mt-3 mb-3 bg-white shadow rounded">
    <h1 class="mb-1">Sjiraffenvers-Generator</h1>
    <div class="p-2">
        <!-- Verse will be loaded here -->
        <p>{{ random_verse.full_verse|linebreaksbr }}</p>
        <p><i>Laget av {{random_verse.creator}}</i></p>
    </div>

    <!-- Logo that acts as a button -->
    <div id="logo-button" class="my-3" onclick="location.reload();">
        <img src="{% static 'undergroups/tåkeluren/tåkeluren_click.png' %}" alt="Generate New Verse" width="180">
    </div>
    <hr>
    <!-- New button to link to Sjiraffenvers page -->
    <div class="row mb-3">
        <div class="col-md-5 mx-auto">
            <a href="{% url 'undergroups:sjiraffenvers_list' %}" class="btn btn-default bg-light mb-3 mt-3">Last inn alle Sjiraffenvers!</a>
        </div>
    </div>
    <hr>
    <div class="row mb-3">
        <div class="col-md-5 mx-auto">
            <a href="{% url 'undergroups:song_list' %}" class="btn btn-default mb-3 mt-3 bg-light">Gamle Tåkelur-viser og Studentsanger!</a>
        </div>
    </div>
    <hr>
    <div class="row mb-4">
        <div class="col-md-5 mb-3 mx-auto">
            <a href="{% url 'undergroups:suggest_sjiraffenvers' %}" class="btn btn-default mb-3 mt-3 bg-light">Lag nytt Sjiraffenvers</a>
        </div>
    </div>
</div>
{% endblock %}