bedriftskontakt/urls.py
from django.urls import path
from . import views

app_name = 'bedriftskontakt'
urlpatterns = [


    path('bedriftspresentasjoner/', views.business_presentations_view, name='business_presentations'),
    path('stillingsannonser/', views.ad_list_view, name='ad_list'),
    path('stillingsannonser/<int:pk>/', views.ad_single_view, name='ad_single'),
    path('stillingsannonser/ny/', views.ad_create_view, name='ad_create'),
    path('annonser/<int:pk>/delete/', views.ad_delete_view, name='ad_delete'),
    path('for-bedriften/', views.for_company_view, name='for_company'),
    path('for-studenten/', views.for_student_view, name='for_student'),
    path('Team-BK/ny/', views.Member_create_view, name='member_create'),
    path('Team-BK/', views.team_bk_view, name='team_bk'),
    path('bedrifter/ny/', views.create_company, name='create_company'),
    path('bedrifter/<int:pk>/endre/', views.edit_company, name='edit_company'),
    path('bedrifter/<int:pk>/slett/', views.delete_company, name='delete_company'),
    path('bedrifter/', views.companyoverview, name='companyoverview'),
    path('bedrifter/<int:pk>/', views.company_details, name='company_details'),
    path('bedrifter/<int:pk>/logg/', views.company_log, name='company_log'),
    path('bedrifter/<int:pk>/logg/ny/', views.company_log_create, name='company_log_create'),
    path('ringeliste/admin/<slug:slug>/', views.call_list_admin, name='call_list_admin'),
    path('ringeliste/<slug:slug>/', views.call_list, name='call_list'),
    path('ringeliste/personlig/<slug:slug>/', views.personal_call_list, name='personal_call_list'),
    path('stillingsannonser/<int:pk>/endre/', views.change_ad, name='change_ad'),
]

news/urls.py
from django.urls import path
from .views import NewsArticleView
from . import views

app_name = 'news'
urlpatterns = [
    path('all/', views.news_all, name='all'),
    path('<slug:link>/', NewsArticleView.as_view(), name="article_page")
]

bedriftskontakt/forms.py
from django import forms
from .models import JobAd, Member, Location, Company, Semester, CompanyLog
from django.forms.widgets import CheckboxSelectMultiple
"""

---These will be added when internal BK pages are being developed---
class CompanyChangeForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = [
            'company_name',
            'company_summary',
            'company_logo'
            'company_homepage',
            'company_contact',
            'company_contact_email',
            'company_contact_phone',
        ]
        labels = {
            'company_name': ('Firmanavn'),
            'company_summary': ('Beskrivelse'),
            'company_logo': ('Logo'),
            'company_homepage': ('Hjemmeside'),
            'company_contact': ('Kontaktperson'),
            'company_contact_email': ('Epost'),
            'company_contact_phone': ('Telefon'),
        }
"""


class CompanyLogAddForm(forms.ModelForm):
    def __init__(self, **kwargs):
        self.log_user = kwargs.pop('log_user', None)
        self.log_timeStamp = kwargs.pop('log_timeStamp', None)
        self.company = kwargs.pop('company', None)
        self.semester = kwargs.pop('semester', None)
        super(CompanyLogAddForm, self).__init__(**kwargs)

    def save(self, commit=True):
        obj = super(CompanyLogAddForm, self).save(commit=False)
        obj.log_user = self.log_user
        obj.log_timeStamp = self.log_timeStamp
        obj.company = self.company
        obj.semester = self.semester
        if commit:
            obj.save()
        return obj

    class Meta:
        model = CompanyLog
        fields = [
            'log_status',
            'log_contact_person',
            'log_contact_info',
            'log_comment',
        ]
        labels = {
            'log_status': ('Status'),
            'log_contact_person:': ('Kontaktperson'),
            'log_contact_info': ('Kontaktinfo (mail eller telefon)'),
            'log_comment': ('Kommentar'),
        }


class CompanyCreationForm(forms.ModelForm):

    class Meta:
        model = Company
        fields = [
            'company_name',
            'company_summary',
            'company_logo',
            'company_homepage',
            'company_contact',
            'company_contact_email',
            'company_contact_phone',
        ]
        labels = {
            'company_name': ('Firmanavn'),
            'company_summary': ('Beskrivelse'),
            'company_logo': ('Logo'),
            'company_homepage': ('Hjemmeside'),
            'company_contact': ('Kontaktperson'),
            'company_contact_email': ('Epost'),
            'company_contact_phone': ('Telefon'),
        }


class JobAdForm(forms.ModelForm):

    location = forms.ModelMultipleChoiceField(queryset=Location.objects.all().order_by(
        'title'), widget=CheckboxSelectMultiple,)

    class Meta:
        model = JobAd
        fields = [
            'company',
            'title',
            'location',
            'deadline',
            'position',
            'description',
            'contact_person',
            'contact_phone',
            'contact_mail',
            'homepage',
            'priority_BK',
            'priority_Mannhullet',
        ]
        labels = {
            'company': ('Firma'),
            'title': ('Tittel'),
            'location': ('Lokasjon'),
            'deadline': ('Frist'),
            'position': ('Stilling'),
            'description': ('Beskrivelse'),
            'contact_person': ('Kontaktperson'),
            'contact_phone': ('Kontaktperson telefon'),
            'contact_mail': ('Mail'),
            'homepage': ('Søknadsside'),
            'priority_BK': ('Prioritert BK'),
            'priority_Mannhullet': ('Prioritert Mannhullet'),
        }


class MemberAddForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = [
            'member_name',
            'member_email',
            'member_image',
            'member_position',
            'member_priority',
        ]
        labels = {
            'member_name': ('Navn'),
            'member_email': ('Email'),
            'member_image': ('Bilde'),
            'member_position': ('Stilling'),
            'member_priority': ('Prioriteringsnummer (Leder=1, nestleder=2, bedriftskontakt=100)'),
        }


class LocationAddForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = [
            'title',
        ]
        labels = {
            'title': ('Ny lokasjon:')
        }


class NewSemesterForm(forms.ModelForm):
    class Meta:
        model = Semester
        fields = [
            'semester'
        ]
        labels = {
            'semester': ('Semester'),
        }


class NewDeadlineForm(forms.Form):
    deadline = forms.DateField(label='Frist')

bedriftskontakt/views.py
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
from bedriftskontakt.forms import JobAdForm, MemberAddForm, LocationAddForm,\
    CompanyCreationForm, NewSemesterForm, NewDeadlineForm, CompanyLogAddForm
from .models import Member, JobAd, Company, CompanyLog, CallList, Semester
from events.models import Event
from django.core.exceptions import PermissionDenied
from django.utils import timezone
from django.urls import reverse
from bedriftskontakt.filters import JobAdFilter, CallListFilter
from datetime import datetime
from django.forms.models import inlineformset_factory
from django.db.models import Q, F
""""
-------This is used for internal BK functions and will be added later when public site is finished------


def change_company(request, pk):
    company = get_object_or_404(Company, pk=pk)
    form = CompanyChangeForm(instance=company)
    if request.method == 'POST':
        form = CompanyChangeForm(data=request.POST, instance=company)
        form.save()
        company.save()
        return HttpResponseRedirect('#')
    return render(request, 'bedriftskontakt/change_company.html', {'form': form, 'company': company})
"""


def has_BK_admin_permission(user):  # Used to check if user is in correct group
    permitted_groups = ['BedriftskontaktAdmin']
    if user.is_superuser:
        return True
    else:
        for group in permitted_groups:
            if user.groups.filter(name=group).exists():
                return True
        return False


def has_BK_permission(user):  # Used to check if user is in correct group
    permitted_groups = ['Bedriftskontakt', 'BedriftskontaktAdmin']
    if user.is_superuser:
        return True
    else:
        for group in permitted_groups:
            if user.groups.filter(name=group).exists():
                return True
        return False


def company_log(request, pk):
    company = get_object_or_404(Company, pk=pk)
    queryset = CompanyLog.objects.all().order_by('-pk')
    user = request.user
    semester_list = Semester.objects.all().order_by('-pk')
    if has_BK_permission(user):
        context = {
            'company': company,
            'company_log_list': queryset,
            'user': user,
            'semester_list': semester_list,
        }
        return render(request, 'bedriftskontakt/company_log.html', context)
    else:
        raise PermissionDenied


def company_log_create(request, pk):
    company = get_object_or_404(Company, pk=pk)
    form = CompanyLogAddForm(instance=company)
    user = request.user
    timeStamp = timezone.now()
    semester = Semester.objects.last()
    if has_BK_permission(user):
        if request.method == 'POST':
            form = CompanyLogAddForm(
                log_user=user, log_timeStamp=timeStamp, company=company, semester=semester, data=request.POST)
            form.save()
            return HttpResponseRedirect(reverse('bedriftskontakt:company_log', args=(pk,)))
        context = {
            'form': form,
            'company': company,
            'semester': semester,
        }
        return render(request, 'bedriftskontakt/company_log_add.html', context)
    else:
        raise PermissionDenied


def call_list(request, slug):
    semester = get_object_or_404(Semester, slug=slug)
    call_list = CallList.objects.filter(semester=semester)
    filter = CallListFilter(request.GET, queryset=call_list)
    company_log_dict = {
        "company": [],
        "log_status": [],
    }
    company_log = CompanyLog.objects.filter(semester=semester).order_by('-log_timeStamp')
    for obj in company_log:
        if obj.company not in company_log_dict["company"]:
            company_log_dict["company"].append(obj.company)
            company_log_dict["log_status"].append(obj.log_status)
    company_log_list_all = []
    i = 0
    for obj in call_list:
        if obj.company in company_log_dict["company"]:
            company_log_list_all.append(company_log_dict["log_status"][company_log_dict["company"].index(obj.company)])
            i += 1
        else:
            company_log_list_all.append("Ikke kontaktet")
    user = request.user
    if has_BK_permission(user):
        context = {
            'semester': semester,
            'call_list': call_list,
            'filter': filter,
            'company_log': company_log,
            'user': user,
            'company_log_list_all': company_log_list_all,
        }
        return render(request, 'bedriftskontakt/call_list.html', context)
    else:
        raise PermissionDenied


def personal_call_list(request, slug):
    user = request.user
    semester = get_object_or_404(Semester, slug=slug)
    call_list = CallList.objects.filter(semester=semester, company_asignee=user)
    company_log_dict = {
        "company": [],
        "log_status": [],
    }
    company_log = CompanyLog.objects.filter(semester=semester).order_by('-log_timeStamp')
    for obj in company_log:
        if obj.company not in company_log_dict["company"]:
            company_log_dict["company"].append(obj.company)
            company_log_dict["log_status"].append(obj.log_status)
    company_log_list_all = []
    i = 0
    for obj in call_list:
        if obj.company in company_log_dict["company"]:
            company_log_list_all.append(company_log_dict["log_status"][company_log_dict["company"].index(obj.company)])
            i += 1
        else:
            company_log_list_all.append("Ikke kontaktet")
    if has_BK_permission(user):
        context = {
            'semester': semester,
            'call_list': call_list,
            'company_log': company_log,
            'user': user,
            'company_log_list_all': company_log_list_all,
        }
        return render(request, 'bedriftskontakt/personal_call_list.html', context)
    else:
        raise PermissionDenied


def call_list_admin(request, slug):
    CallListFormSet = inlineformset_factory(Semester, CallList, fields=(
         'company_asignee', 'deadline',), extra=0, can_delete=False)
    company_list = Company.objects.all()
    semester = get_object_or_404(Semester, slug=slug)
    call_list = CallList.objects.filter(semester=semester)
    filter = CallListFilter(request.GET, queryset=call_list)
    formset = CallListFormSet(instance=semester)
    form = NewSemesterForm
    form_deadline = NewDeadlineForm
    user = request.user
    semester_list = Semester.objects.all()
    if has_BK_admin_permission(user):
        if request.method == 'POST' and 'asigneebtn' in request.POST:
            formset = CallListFormSet(request.POST, instance=semester)
            call_list = CallList.objects.filter(semester=semester)
            filter = CallListFilter(request.GET, queryset=call_list)
            formset.save()
            return HttpResponseRedirect(reverse('bedriftskontakt:call_list_admin', args=(slug,)))
        if request.method == 'POST' and 'newsemesterbtn' in request.POST:
            form = NewSemesterForm(request.POST)
            form.save()
            newSemester = Semester.objects.last()
            for company in company_list:
                CallList.objects.create_CallList(company=company, semester=newSemester)
            return HttpResponseRedirect(reverse('bedriftskontakt:call_list_admin', args=(newSemester.slug,)))
        if request.method == 'POST' and 'newdeadline' in request.POST:
            form_deadline = NewDeadlineForm(request.POST)
            if form_deadline.is_valid():
                deadline = form_deadline.cleaned_data['deadline']
                CallList.objects.change_deadline(deadline)
                return HttpResponseRedirect(reverse('bedriftskontakt:call_list_admin', args=(slug,)))
        context = {
            'call_list': call_list,
            'filter': filter,
            'company_list': company_list,
            'semester': semester,
            'formset': formset,
            'form': form,
            'semester_list': semester_list,
            'form_deadline': form_deadline,
            }
        return render(request, 'bedriftskontakt/call_list_admin.html', context)
    else:
        raise PermissionDenied


def create_company(request):
    form = CompanyCreationForm
    user = request.user
    if has_BK_permission(user):
        if request.method == 'POST':
            form = CompanyCreationForm(request.POST, request.FILES)
            form.save()
            newcompany = Company.objects.order_by('pk').last()
            semester = Semester.objects.last()
            CallList.objects.create_CallList(company=newcompany, semester=semester)
            return HttpResponseRedirect('/bedriftskontakt/bedrifter/')
        return render(request, 'bedriftskontakt/company/create_company.html', {'form': form})
    else:
        raise PermissionDenied


def edit_company(request, pk):
    company = get_object_or_404(Company, pk=pk)
    form = CompanyCreationForm(instance=company)
    user = request.user
    if has_BK_permission(user):
        if request.method == 'POST':
            form = CompanyCreationForm(request.POST, request.FILES, instance=company)
            form.save()
            return HttpResponseRedirect(reverse('bedriftskontakt:company_details', args=(pk,)))
        return render(request, 'bedriftskontakt/company/edit_company.html', {'form': form})
    else:
        raise PermissionDenied


def delete_company(request, pk):
    if request.method == 'POST':
        user = request.user
        if has_BK_admin_permission(user):
            company = get_object_or_404(Company, pk=pk)
            company.delete()
            return HttpResponseRedirect(reverse('bedriftskontakt:companyoverview'))
        else:
            raise PermissionDenied
    else:
        raise Http404


def team_bk_view(request):
    queryset = Member.objects.order_by("member_priority")
    context = {
        'members': queryset,
    }
    return render(request, 'bedriftskontakt/team_bk.html', context)

templates/bedriftskontakt/company/company_details.html
{% extends '../base_bk.html' %}
{% load static %}
{% block info %}
<br><br>
<div class="align-items-end">
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
      <h1 class="row justify-content-center">{{company.company_name}}</h1>
    </div>
    <div class="col-md-3">
      <a class="btn btn-primary float-left align-center button-company" href="{% url 'bedriftskontakt:edit_company' pk=company.pk%}">Endre</a>
      <form action="{% url 'bedriftskontakt:delete_company' company.pk %}" method="post">
        {% csrf_token %}
        <button class="btn btn-danger button-company float-right align-center event-delete-btn">
          Slett
        </button>
      </form>
    </div>
  </div>
</div>
<hr class="py-2">

<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="blue-company">
        <h3>Kontaktinformasjon</h3>
        <hr class="py-2">
        <div class="row">
          <div class="col-md-12">
            <strong>Kontaktperson:</strong> {{company.company_contact}}<br><br>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <strong>Mail:</strong> {{company.company_contact_email}}<br><br>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <strong>Tlf:</strong> {{company.company_contact_phone}}<br><br>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <strong>Hjemmeside:</strong> <a href="{{company.company_homepage}}" target="_blank" >Link</a><br><br>
          </div>
        </div>
      </div>

    </div>
    <div class="col-md-1">
    </div>
    <div class="col-md-7">
      <div class="blue-company">
        <h3>Om bedriften</h3>
        <hr class="py-2">
        <div class="row">
          <div class="col-md-8">
            {{ company.company_summary|safe}}
          </div>
          <div class="col-md-4">
              <img class = "img-fluid" {% if company.company_logo %} src="{{ company.company_logo.url }}" {% else %} src = "" {% endif %} alt="{{ company.company_name }} logo">
          </div>
        </div>
      </div>
    </div>
  </div>
  <br><br>
</div>

<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>

<script>
  $(document).on('click', '.event-delete-btn', function(){
      return confirm('Er du sikker på at du vil slette denne bedriften?');
  })
</script>


{% endblock %}

templates/bedriftskontakt/company/companyoverview.html
{% extends '../base_bk.html' %}

{% block title %} Bedrifter {% endblock %}
{% block info%}
{% load static %}
{% load app_filters %}
<!--Image top-->
<br><br>
<div class="row align-items-end">
  <div class="col-md-3">
  </div>
  <div class="col-md-6">
    <h1 class="row justify-content-center">Bedriftliste</h1>
  </div>
  <div class="col-md-3">
    <a class="btn btn-primary float-right align-center button-company" href="{% url 'bedriftskontakt:create_company'%}">Lag ny bedrift</a>
  </div>
</div>
<hr class="py-2">
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4 text-left">
      <h2>Bedrift</h2>
    </div>
    <div class="col-md-3 text-left">
      <h2>Til bedrift</h2>
    </div>
    <div class="col-md-3 text-left">
      <h2>Logg</h2>
    </div>
    <div class="col-md-2 text-left">
      {% if request.user|has_BK_admin_permission %}
      <h2>Slett</h2>
      {% endif %}
    </div>
  </div>

  {% for company in company_list %}
    <div class="row company-overview">
      <div class="col-md-4 text-left">
        <h3>{{company.company_name}}</h3>
      </div>
      <div class="col-md-3 text-left">
        <a class="btn btn-primary float-left align-center button-company" href="{% url 'bedriftskontakt:company_details' pk=company.pk %}">Bedrift</a>
      </div>
      <div class="col-md-3 text-left">
        <a class="btn btn-primary float-left align-center button-company" href="{% url 'bedriftskontakt:company_log' pk=company.pk %}">Logg</a>
      </div>
      <div class="col-md-2 text-left">
        {% if request.user|has_BK_admin_permission %}
        <form action="{% url 'bedriftskontakt:delete_company' company.pk %}" method="post">
          {% csrf_token %}
          <button class="btn btn-danger button-company float-left align-center event-delete-btn">
            Slett
          </button>
        </form>
        {% endif %}
      </div>
    </div>
  {% endfor %}


</div>

<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>

<script type="text/javascript">
  $('.company-overview')
    .filter(":even")
    .addClass('grey-color')
</script>

<script>
  $(document).on('click', '.event-delete-btn', function(){
      return confirm('Er du sikker på at du vil slette denne bedriften?');
  })
</script>

{% endblock %}

templates/bedriftskontakt/company/create_company.html
{% extends '../base_bk.html' %}

{% block title %}Registrere nytt Firma{% endblock %}

{% block content %}
{% load static %}
<div id="container" class="container" style="padding-top: 5px;">
  <div class="row">
    <div class="col-sm-offset-0 col-sm-8 col-md-offset-1 col-md-6">
      <h3> Registrer Firma </h3>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
        <h3>{{ field.label_tag }}</h3>
        <p>{{ field }}</p>
        <p>{{field.help_text}}</p>
        <p>{{field.errors}}</p>

        {% endfor %}
        <button class="btn btn-default" type="submit" style="width:100%"
        >Lagre</button>
      </form>
    </div>
  </div>
</div>
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugin/tinymce/tinymce.min.js' %}" ></script>
<script type="text/javascript" src= "{% static 'plugin/tinymce/init-tinymce.js' %}"></script>
{% endblock %}

templates/bedriftskontakt/company/edit_company.html
{% extends '../base_bk.html' %}

{% block title %}Endre Firma{% endblock %}

{% block content %}
{% load static %}
<div id="container" class="container" style="padding-top: 5px;">
  <div class="row">
    <div class="col-sm-offset-0 col-sm-8 col-md-offset-1 col-md-6">
      <h3> Endre Firma </h3>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
        <h3>{{ field.label_tag }}</h3>
        <p>{{ field }}</p>
        <p>{{field.help_text}}</p>
        <p>{{field.errors}}</p>

        {% endfor %}
        <button class="btn btn-default" type="submit" style="width:100%"
        >Lagre</button>
      </form>
    </div>
  </div>
</div>
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugin/tinymce/tinymce.min.js' %}" ></script>
<script type="text/javascript" src= "{% static 'plugin/tinymce/init-tinymce.js' %}"></script>
{% endblock %}