bedriftskontakt/urls.py
from django.urls import path
from . import views

app_name = 'bedriftskontakt'
urlpatterns = [


    path('bedriftspresentasjoner/', views.business_presentations_view, name='business_presentations'),
    path('stillingsannonser/', views.ad_list_view, name='ad_list'),
    path('stillingsannonser/<int:pk>/', views.ad_single_view, name='ad_single'),
    path('stillingsannonser/ny/', views.ad_create_view, name='ad_create'),
    path('annonser/<int:pk>/delete/', views.ad_delete_view, name='ad_delete'),
    path('for-bedriften/', views.for_company_view, name='for_company'),
    path('for-studenten/', views.for_student_view, name='for_student'),
    path('Team-BK/ny/', views.Member_create_view, name='member_create'),
    path('Team-BK/', views.team_bk_view, name='team_bk'),
    path('bedrifter/ny/', views.create_company, name='create_company'),
    path('bedrifter/<int:pk>/endre/', views.edit_company, name='edit_company'),
    path('bedrifter/<int:pk>/slett/', views.delete_company, name='delete_company'),
    path('bedrifter/', views.companyoverview, name='companyoverview'),
    path('bedrifter/<int:pk>/', views.company_details, name='company_details'),
    path('bedrifter/<int:pk>/logg/', views.company_log, name='company_log'),
    path('bedrifter/<int:pk>/logg/ny/', views.company_log_create, name='company_log_create'),
    path('ringeliste/admin/<slug:slug>/', views.call_list_admin, name='call_list_admin'),
    path('ringeliste/<slug:slug>/', views.call_list, name='call_list'),
    path('ringeliste/personlig/<slug:slug>/', views.personal_call_list, name='personal_call_list'),
    path('stillingsannonser/<int:pk>/endre/', views.change_ad, name='change_ad'),
]

news/urls.py
from django.urls import path
from .views import NewsArticleView
from . import views

app_name = 'news'
urlpatterns = [
    path('all/', views.news_all, name='all'),
    path('<slug:link>/', NewsArticleView.as_view(), name="article_page")
]

bedriftskontakt/forms.py
from django import forms
from .models import JobAd, Member, Location, Company, Semester, CompanyLog
from django.forms.widgets import CheckboxSelectMultiple
"""

---These will be added when internal BK pages are being developed---
class CompanyChangeForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = [
            'company_name',
            'company_summary',
            'company_logo'
            'company_homepage',
            'company_contact',
            'company_contact_email',
            'company_contact_phone',
        ]
        labels = {
            'company_name': ('Firmanavn'),
            'company_summary': ('Beskrivelse'),
            'company_logo': ('Logo'),
            'company_homepage': ('Hjemmeside'),
            'company_contact': ('Kontaktperson'),
            'company_contact_email': ('Epost'),
            'company_contact_phone': ('Telefon'),
        }
"""


class CompanyLogAddForm(forms.ModelForm):
    def __init__(self, **kwargs):
        self.log_user = kwargs.pop('log_user', None)
        self.log_timeStamp = kwargs.pop('log_timeStamp', None)
        self.company = kwargs.pop('company', None)
        self.semester = kwargs.pop('semester', None)
        super(CompanyLogAddForm, self).__init__(**kwargs)

    def save(self, commit=True):
        obj = super(CompanyLogAddForm, self).save(commit=False)
        obj.log_user = self.log_user
        obj.log_timeStamp = self.log_timeStamp
        obj.company = self.company
        obj.semester = self.semester
        if commit:
            obj.save()
        return obj

    class Meta:
        model = CompanyLog
        fields = [
            'log_status',
            'log_contact_person',
            'log_contact_info',
            'log_comment',
        ]
        labels = {
            'log_status': ('Status'),
            'log_contact_person:': ('Kontaktperson'),
            'log_contact_info': ('Kontaktinfo (mail eller telefon)'),
            'log_comment': ('Kommentar'),
        }


class CompanyCreationForm(forms.ModelForm):

    class Meta:
        model = Company
        fields = [
            'company_name',
            'company_summary',
            'company_logo',
            'company_homepage',
            'company_contact',
            'company_contact_email',
            'company_contact_phone',
        ]
        labels = {
            'company_name': ('Firmanavn'),
            'company_summary': ('Beskrivelse'),
            'company_logo': ('Logo'),
            'company_homepage': ('Hjemmeside'),
            'company_contact': ('Kontaktperson'),
            'company_contact_email': ('Epost'),
            'company_contact_phone': ('Telefon'),
        }


class JobAdForm(forms.ModelForm):

    location = forms.ModelMultipleChoiceField(queryset=Location.objects.all().order_by(
        'title'), widget=CheckboxSelectMultiple,)

    class Meta:
        model = JobAd
        fields = [
            'company',
            'title',
            'location',
            'deadline',
            'position',
            'description',
            'contact_person',
            'contact_phone',
            'contact_mail',
            'homepage',
            'priority_BK',
            'priority_Mannhullet',
        ]
        labels = {
            'company': ('Firma'),
            'title': ('Tittel'),
            'location': ('Lokasjon'),
            'deadline': ('Frist'),
            'position': ('Stilling'),
            'description': ('Beskrivelse'),
            'contact_person': ('Kontaktperson'),
            'contact_phone': ('Kontaktperson telefon'),
            'contact_mail': ('Mail'),
            'homepage': ('Søknadsside'),
            'priority_BK': ('Prioritert BK'),
            'priority_Mannhullet': ('Prioritert Mannhullet'),
        }


class MemberAddForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = [
            'member_name',
            'member_email',
            'member_image',
            'member_position',
            'member_priority',
        ]
        labels = {
            'member_name': ('Navn'),
            'member_email': ('Email'),
            'member_image': ('Bilde'),
            'member_position': ('Stilling'),
            'member_priority': ('Prioriteringsnummer (Leder=1, nestleder=2, bedriftskontakt=100)'),
        }


class LocationAddForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = [
            'title',
        ]
        labels = {
            'title': ('Ny lokasjon:')
        }


class NewSemesterForm(forms.ModelForm):
    class Meta:
        model = Semester
        fields = [
            'semester'
        ]
        labels = {
            'semester': ('Semester'),
        }


class NewDeadlineForm(forms.Form):
    deadline = forms.DateField(label='Frist')

bedriftskontakt/views.py
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
from bedriftskontakt.forms import JobAdForm, MemberAddForm, LocationAddForm,\
    CompanyCreationForm, NewSemesterForm, NewDeadlineForm, CompanyLogAddForm
from .models import Member, JobAd, Company, CompanyLog, CallList, Semester
from events.models import Event
from django.core.exceptions import PermissionDenied
from django.utils import timezone
from django.urls import reverse
from bedriftskontakt.filters import JobAdFilter, CallListFilter
from datetime import datetime
from django.forms.models import inlineformset_factory
from django.db.models import Q, F
""""
-------This is used for internal BK functions and will be added later when public site is finished------


def change_company(request, pk):
    company = get_object_or_404(Company, pk=pk)
    form = CompanyChangeForm(instance=company)
    if request.method == 'POST':
        form = CompanyChangeForm(data=request.POST, instance=company)
        form.save()
        company.save()
        return HttpResponseRedirect('#')
    return render(request, 'bedriftskontakt/change_company.html', {'form': form, 'company': company})
"""


def has_BK_admin_permission(user):  # Used to check if user is in correct group
    permitted_groups = ['BedriftskontaktAdmin']
    if user.is_superuser:
        return True
    else:
        for group in permitted_groups:
            if user.groups.filter(name=group).exists():
                return True
        return False


def has_BK_permission(user):  # Used to check if user is in correct group
    permitted_groups = ['Bedriftskontakt', 'BedriftskontaktAdmin']
    if user.is_superuser:
        return True
    else:
        for group in permitted_groups:
            if user.groups.filter(name=group).exists():
                return True
        return False


def company_log(request, pk):
    company = get_object_or_404(Company, pk=pk)
    queryset = CompanyLog.objects.all().order_by('-pk')
    user = request.user
    semester_list = Semester.objects.all().order_by('-pk')
    if has_BK_permission(user):
        context = {
            'company': company,
            'company_log_list': queryset,
            'user': user,
            'semester_list': semester_list,
        }
        return render(request, 'bedriftskontakt/company_log.html', context)
    else:
        raise PermissionDenied


def company_log_create(request, pk):
    company = get_object_or_404(Company, pk=pk)
    form = CompanyLogAddForm(instance=company)
    user = request.user
    timeStamp = timezone.now()
    semester = Semester.objects.last()
    if has_BK_permission(user):
        if request.method == 'POST':
            form = CompanyLogAddForm(
                log_user=user, log_timeStamp=timeStamp, company=company, semester=semester, data=request.POST)
            form.save()
            return HttpResponseRedirect(reverse('bedriftskontakt:company_log', args=(pk,)))
        context = {
            'form': form,
            'company': company,
            'semester': semester,
        }
        return render(request, 'bedriftskontakt/company_log_add.html', context)
    else:
        raise PermissionDenied


def call_list(request, slug):
    semester = get_object_or_404(Semester, slug=slug)
    call_list = CallList.objects.filter(semester=semester)
    filter = CallListFilter(request.GET, queryset=call_list)
    company_log_dict = {
        "company": [],
        "log_status": [],
    }
    company_log = CompanyLog.objects.filter(semester=semester).order_by('-log_timeStamp')
    for obj in company_log:
        if obj.company not in company_log_dict["company"]:
            company_log_dict["company"].append(obj.company)
            company_log_dict["log_status"].append(obj.log_status)
    company_log_list_all = []
    i = 0
    for obj in call_list:
        if obj.company in company_log_dict["company"]:
            company_log_list_all.append(company_log_dict["log_status"][company_log_dict["company"].index(obj.company)])
            i += 1
        else:
            company_log_list_all.append("Ikke kontaktet")
    user = request.user
    if has_BK_permission(user):
        context = {
            'semester': semester,
            'call_list': call_list,
            'filter': filter,
            'company_log': company_log,
            'user': user,
            'company_log_list_all': company_log_list_all,
        }
        return render(request, 'bedriftskontakt/call_list.html', context)
    else:
        raise PermissionDenied


def personal_call_list(request, slug):
    user = request.user
    semester = get_object_or_404(Semester, slug=slug)
    call_list = CallList.objects.filter(semester=semester, company_asignee=user)
    company_log_dict = {
        "company": [],
        "log_status": [],
    }
    company_log = CompanyLog.objects.filter(semester=semester).order_by('-log_timeStamp')
    for obj in company_log:
        if obj.company not in company_log_dict["company"]:
            company_log_dict["company"].append(obj.company)
            company_log_dict["log_status"].append(obj.log_status)
    company_log_list_all = []
    i = 0
    for obj in call_list:
        if obj.company in company_log_dict["company"]:
            company_log_list_all.append(company_log_dict["log_status"][company_log_dict["company"].index(obj.company)])
            i += 1
        else:
            company_log_list_all.append("Ikke kontaktet")
    if has_BK_permission(user):
        context = {
            'semester': semester,
            'call_list': call_list,
            'company_log': company_log,
            'user': user,
            'company_log_list_all': company_log_list_all,
        }
        return render(request, 'bedriftskontakt/personal_call_list.html', context)
    else:
        raise PermissionDenied


def call_list_admin(request, slug):
    CallListFormSet = inlineformset_factory(Semester, CallList, fields=(
         'company_asignee', 'deadline',), extra=0, can_delete=False)
    company_list = Company.objects.all()
    semester = get_object_or_404(Semester, slug=slug)
    call_list = CallList.objects.filter(semester=semester)
    filter = CallListFilter(request.GET, queryset=call_list)
    formset = CallListFormSet(instance=semester)
    form = NewSemesterForm
    form_deadline = NewDeadlineForm
    user = request.user
    semester_list = Semester.objects.all()
    if has_BK_admin_permission(user):
        if request.method == 'POST' and 'asigneebtn' in request.POST:
            formset = CallListFormSet(request.POST, instance=semester)
            call_list = CallList.objects.filter(semester=semester)
            filter = CallListFilter(request.GET, queryset=call_list)
            formset.save()
            return HttpResponseRedirect(reverse('bedriftskontakt:call_list_admin', args=(slug,)))
        if request.method == 'POST' and 'newsemesterbtn' in request.POST:
            form = NewSemesterForm(request.POST)
            form.save()
            newSemester = Semester.objects.last()
            for company in company_list:
                CallList.objects.create_CallList(company=company, semester=newSemester)
            return HttpResponseRedirect(reverse('bedriftskontakt:call_list_admin', args=(newSemester.slug,)))
        if request.method == 'POST' and 'newdeadline' in request.POST:
            form_deadline = NewDeadlineForm(request.POST)
            if form_deadline.is_valid():
                deadline = form_deadline.cleaned_data['deadline']
                CallList.objects.change_deadline(deadline)
                return HttpResponseRedirect(reverse('bedriftskontakt:call_list_admin', args=(slug,)))
        context = {
            'call_list': call_list,
            'filter': filter,
            'company_list': company_list,
            'semester': semester,
            'formset': formset,
            'form': form,
            'semester_list': semester_list,
            'form_deadline': form_deadline,
            }
        return render(request, 'bedriftskontakt/call_list_admin.html', context)
    else:
        raise PermissionDenied


def create_company(request):
    form = CompanyCreationForm
    user = request.user
    if has_BK_permission(user):
        if request.method == 'POST':
            form = CompanyCreationForm(request.POST, request.FILES)
            form.save()
            newcompany = Company.objects.order_by('pk').last()
            semester = Semester.objects.last()
            CallList.objects.create_CallList(company=newcompany, semester=semester)
            return HttpResponseRedirect('/bedriftskontakt/bedrifter/')
        return render(request, 'bedriftskontakt/company/create_company.html', {'form': form})
    else:
        raise PermissionDenied


def edit_company(request, pk):
    company = get_object_or_404(Company, pk=pk)
    form = CompanyCreationForm(instance=company)
    user = request.user
    if has_BK_permission(user):
        if request.method == 'POST':
            form = CompanyCreationForm(request.POST, request.FILES, instance=company)
            form.save()
            return HttpResponseRedirect(reverse('bedriftskontakt:company_details', args=(pk,)))
        return render(request, 'bedriftskontakt/company/edit_company.html', {'form': form})
    else:
        raise PermissionDenied


def delete_company(request, pk):
    if request.method == 'POST':
        user = request.user
        if has_BK_admin_permission(user):
            company = get_object_or_404(Company, pk=pk)
            company.delete()
            return HttpResponseRedirect(reverse('bedriftskontakt:companyoverview'))
        else:
            raise PermissionDenied
    else:
        raise Http404


def team_bk_view(request):
    queryset = Member.objects.order_by("member_priority")
    context = {
        'members': queryset,
    }
    return render(request, 'bedriftskontakt/team_bk.html', context)

templates/bedriftskontakt/ad/ad_bk_list.html
{% load static %}

{% block app_css %}<link rel="stylesheet" href={% static "/bedriftskontakt/css/bedriftskontakt.css" %}>{% endblock %}


<a class="job-ad" href="{% url 'bedriftskontakt:ad_single' pk=ad.pk %}">
  <div class="card my-4">
  <div class="card-header bg-jobadcard card-round-edge">
    <div class="card-title">
        <h4 class="text-center text-white"><a href="{% url 'bedriftskontakt:ad_single' pk=ad.pk %}"
            class="stretched-link text-light">{{ad.company}} -  {{ad.title}}</a>
      </h4>
    </div>
  </div>
  <div class="card-body">
    <div class="card-text flew-row">
      <div class="col-sm-12 col-md-6 pull-left">
        <p>
          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-calendar-date" fill="currentColor"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z" />
            <path
              d="M6.445 11.688V6.354h-.633A12.6 12.6 0 0 0 4.5 7.16v.695c.375-.257.969-.62 1.258-.777h.012v4.61h.675zm1.188-1.305c.047.64.594 1.406 1.703 1.406 1.258 0 2-1.066 2-2.871 0-1.934-.781-2.668-1.953-2.668-.926 0-1.797.672-1.797 1.809 0 1.16.824 1.77 1.676 1.77.746 0 1.23-.376 1.383-.79h.027c-.004 1.316-.461 2.164-1.305 2.164-.664 0-1.008-.45-1.05-.82h-.684zm2.953-2.317c0 .696-.559 1.18-1.184 1.18-.601 0-1.144-.383-1.144-1.2 0-.823.582-1.21 1.168-1.21.633 0 1.16.398 1.16 1.23z" />
          </svg>
          &nbsp;
          <strong> Frist: </strong>{{ad.deadline}}</p>
        <p><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-geo-alt-fill" fill="currentColor"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
          </svg>
          &nbsp;
          <strong> Sted: </strong>{% if ad.location.count == 1%} {{ad.location.last}} {% else %}Flere {% endif %}</p>
        <p>
          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-people" fill="currentColor"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M15 14s1 0 1-1-1-4-5-4-5 3-5 4 1 1 1 1h8zm-7.978-1h7.956a.274.274 0 0 0 .014-.002l.008-.002c-.002-.264-.167-1.03-.76-1.72C13.688 10.629 12.718 10 11 10c-1.717 0-2.687.63-3.24 1.276-.593.69-.759 1.457-.76 1.72a1.05 1.05 0 0 0 .022.004zM11 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0zM6.936 9.28a5.88 5.88 0 0 0-1.23-.247A7.35 7.35 0 0 0 5 9c-4 0-5 3-5 4 0 .667.333 1 1 1h4.216A2.238 2.238 0 0 1 5 13c0-1.01.377-2.042 1.09-2.904.243-.294.526-.569.846-.816zM4.92 10c-1.668.02-2.615.64-3.16 1.276C1.163 11.97 1 12.739 1 13h3c0-1.045.323-2.086.92-3zM1.5 5.5a3 3 0 1 1 6 0 3 3 0 0 1-6 0zm3-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4z" />
          </svg>
          &nbsp;
          <strong> Stilling: </strong>{{ad.position}}</p>
      </div>
      <div class="col-md-12 col-sm-12 col-xs-12 jobad-box">
        <img class=" float-right frontpage-image" {% if ad.company.company_logo %} src="{{ad.company.company_logo.url}}" {% else %} src = "" {% endif %} alt="Company logo">
      </div>
    </div>
  </div>
</div>
</a>

templates/bedriftskontakt/ad/ad_frontpage.html
{% load static %}

{% block app_css %}<link rel="stylesheet" href={% static "/bedriftskontakt/css/bedriftskontakt.css" %}>{% endblock %}


<a class="job-ad" href="{% url 'bedriftskontakt:ad_single' pk=ad.pk %}">
  <div class="card my-4">
  <div class="card-header bg-jobadcard card-round-edge">
    <div class="card-title">
        <h4 class="text-center text-white"><a href="{% url 'bedriftskontakt:ad_single' pk=ad.pk %}"
            class="stretched-link text-light">{{ad.company}} -  {{ad.title|truncatechars:17}}</a>
      </h4>
    </div>
  </div>
  <div class="card-body">
    <div class="card-text flew-row">
      <div class="col-sm-12 col-md-6 pull-left">
        <p>
          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-calendar-date" fill="currentColor"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z" />
            <path
              d="M6.445 11.688V6.354h-.633A12.6 12.6 0 0 0 4.5 7.16v.695c.375-.257.969-.62 1.258-.777h.012v4.61h.675zm1.188-1.305c.047.64.594 1.406 1.703 1.406 1.258 0 2-1.066 2-2.871 0-1.934-.781-2.668-1.953-2.668-.926 0-1.797.672-1.797 1.809 0 1.16.824 1.77 1.676 1.77.746 0 1.23-.376 1.383-.79h.027c-.004 1.316-.461 2.164-1.305 2.164-.664 0-1.008-.45-1.05-.82h-.684zm2.953-2.317c0 .696-.559 1.18-1.184 1.18-.601 0-1.144-.383-1.144-1.2 0-.823.582-1.21 1.168-1.21.633 0 1.16.398 1.16 1.23z" />
          </svg>
          &nbsp;
          <strong> Frist: </strong>{{ad.deadline}}</p>
        <p><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-geo-alt-fill" fill="currentColor"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
          </svg>
          &nbsp;
          <strong> Sted: </strong>{% if ad.location.count == 1%} {{ad.location.last}} {% else %}Flere {% endif %}</p>
        <p>
          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-people" fill="currentColor"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M15 14s1 0 1-1-1-4-5-4-5 3-5 4 1 1 1 1h8zm-7.978-1h7.956a.274.274 0 0 0 .014-.002l.008-.002c-.002-.264-.167-1.03-.76-1.72C13.688 10.629 12.718 10 11 10c-1.717 0-2.687.63-3.24 1.276-.593.69-.759 1.457-.76 1.72a1.05 1.05 0 0 0 .022.004zM11 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0zM6.936 9.28a5.88 5.88 0 0 0-1.23-.247A7.35 7.35 0 0 0 5 9c-4 0-5 3-5 4 0 .667.333 1 1 1h4.216A2.238 2.238 0 0 1 5 13c0-1.01.377-2.042 1.09-2.904.243-.294.526-.569.846-.816zM4.92 10c-1.668.02-2.615.64-3.16 1.276C1.163 11.97 1 12.739 1 13h3c0-1.045.323-2.086.92-3zM1.5 5.5a3 3 0 1 1 6 0 3 3 0 0 1-6 0zm3-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4z" />
          </svg>
          &nbsp;
          <strong> Stilling: </strong>{{ad.position}}</p>
      </div>
      <div class="col-md-12 col-sm-12 col-xs-12 jobad-box">
        <img class=" float-right frontpage-image" {% if ad.company.company_logo %} src="{{ad.company.company_logo.url}}" {% else %} src = "" {% endif %} alt="Company logo">
      </div>
    </div>
  </div>
</div>
</a>

templates/bedriftskontakt/ad/ad_single.html
{% extends '../base_bk.html' %}
{% load static %}
{% load app_filters %}
{% block info %}
{%  if request.user|has_BK_permission%}
  <div class="row">
    <div class="col-md-8">
    </div>
    <div class="col-md-2">
      <a class="btn button-company align-center float-right" href="{% url 'bedriftskontakt:change_ad' pk=ad.pk %}">Endre</a>
    </div>
    <div class="col-md-2">
      <form action="{% url 'bedriftskontakt:ad_delete' ad.pk %}" method="post">
        {% csrf_token %}
        <button class="btn btn-danger button-company  float-left align-center job-ad-delete-btn">
          Slett
        </button>
      </form>
    </div>
  </div>
{% endif %}
<div class="container event-detail-container">
  <div class="row">
    <div class="col-md-8 col-sm-12">
      <div class="event-block">
        <div class="row">
          <div class="col-sm-12 col-md-12">
            {{ ad.description|safe }}
          </div>
        </div>
      </div>
      <div class="event-block">
        <div class="row">
          <div class=" col-sm-12 col-md-12">
            <h2>Om {{ad.company.company_name}}</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-9 col-md-9">
            {{ ad.company.company_summary|safe }}
          </div>
          <div class="col-md-3 col-sm-3">
            <img class = "img-fluid" {% if ad.company.company_logo %} src="{{ ad.company.company_logo.url }}" {% else %} src = "" {% endif %} alt="{{ ad.company.company_name }} logo">
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4 col-sm-12">
      <div class="event-block">
        <div class="row">
          <div class=" col-sm-12 col-md-12">
            <strong>{{ad.title }}</strong> <br>
            <hr class = "py-1">
            <strong>Bedrift: </strong> {{ad.company.company_name }} <br>
            <strong>Stilling: </strong> {{ad.position }} <br>
            <strong>Lokasjon: </strong> {% for obj in ad.location.all %} {{obj}}{% if obj != ad.location.all.last %},{% endif %} {% endfor %} <br>
            <strong>Søknadsfrist: </strong> {{ad.deadline}} <br>
            {% if ad.contact_person %}
              <strong>Kontaktperson: </strong> {{ad.contact_person}} <br>
            {% endif %}
            {% if ad.contact_mail %}
              <strong>Email: </strong> <a href="{{ad.contact_mail}}">{{ad.contact_mail}}</a> <br>
            {% endif %}
            {% if ad.contact_phone %}
              <strong>Telefon: </strong> {{ad.contact_phone}} <br>
            {% endif %}
            <div class="row pl-2 pr-2">
              <a href= "{{ ad.homepage }}" class = "btn btn-block" style="border: solid black;">
                  <strong>Søk Stilling</strong>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugin/tinymce/tinymce.min.js' %}" ></script>
<script type="text/javascript" src= "{% static 'plugin/tinymce/init-tinymce.js' %}"></script>

<script>
  $(document).on('click', '.job-ad-delete-btn', function(){
      return confirm('Er du sikker på at du vil slette denne stillingsannonsen?');
  })
</script>

{% endblock %}