events/urls.py
from django.urls import path
from . import views

app_name = 'events'
urlpatterns = [
    path('', views.calendar_view, name='calendar'),
    path('<int:year>/<int:month>/', views.calendar_view, name="calendar_month"),
    path('<int:pk>/slett/', views.delete_event, name='delete_event'),
    path('opprett/', views.create_event, name='create_event'),
    path('<int:pk>/endre/', views.change_event, name='change_event'),
    path('<int:pk>/', views.event_details, name='event_details'),
    path('<int:pk>/register/<str:email>', views.register_attendance, name='register_attendance'),
    path('<int:pk>/remove/<str:email>', views.remove_attendance, name='remove_attendance'),
    path('<int:pk>/register_dot/<str:email>', views.register_dots, name='register_dots'),
    path('<int:pk>/export_attendees', views.export_attendees, name='export_attendees'),
    path('liste/', views.events, name='events')
]

news/urls.py
from django.urls import path
from .views import NewsArticleView
from . import views

app_name = 'news'
urlpatterns = [
    path('all/', views.news_all, name='all'),
    path('<slug:link>/', NewsArticleView.as_view(), name="article_page")
]

events/forms.py
from django import forms
from .models import Event, EventConfig
from django.contrib.admin import widgets
from users.models import Mannhullitt


class EventForm(forms.ModelForm):
    start_time = forms.SplitDateTimeField(
        required=False,
        widget=widgets.AdminSplitDateTime,
        label='Starttidspunkt')
    end_time = forms.SplitDateTimeField(
        required=False,
        widget=widgets.AdminSplitDateTime,
        label='Slutttidspunkt')
    registration_starts = forms.SplitDateTimeField(
        required=False,
        widget=widgets.AdminSplitDateTime,
        label='Påmelding starter')
    registration_ends = forms.SplitDateTimeField(
        required=False,
        widget=widgets.AdminSplitDateTime,
        label='Påmelding slutter')
    invited_years = forms.MultipleChoiceField(
        choices=Mannhullitt.YEAR_CHOICES,
        widget=forms.CheckboxSelectMultiple(),
        label='Inviterte')

    SPECIAL_EVENTS = (
        ('ingen', 'Ingen'),
        ('ruka', 'RUKA'),
        ('jubileum', 'Jubileum'),
        ('bedriftsdagen', 'Bedriftsdagen'),
    )

    special_event = forms.CharField(label='Velg spesielt arrangement',
                                    widget=forms.Select(choices=SPECIAL_EVENTS))

    def clean_invited_years(self):
        invited_years = self.cleaned_data['invited_years']
        return ''.join(invited_years)

    def clean(self):
        end_time = self.cleaned_data.get('end_time')
        start_time = self.cleaned_data.get('start_time')
        registration = self.cleaned_data.get('registration')
        registration_starts = self.cleaned_data.get('registration_starts')
        registration_ends = self.cleaned_data.get('registration_ends')

        if end_time is None:
            self._errors['end_time'] = self.error_class(['Slutttidspunkt må spesifiseres'])
        if start_time is None:
            self._errors['start_time'] = self.error_class(['Starttidspunkt må spesifiseres'])

        if end_time is not None and start_time is not None:
            if start_time > end_time:
                self._errors['start_time'] = self.error_class(['Starttidspunkt må være før avslutningstidspunkt'])

        if registration:
            if registration_starts is None:
                self._errors['registration_starts'] = self.error_class(
                    ['Starttidspunkt for påmelding må spesifiseres for påmeldingsarrangement'])
            if registration_ends is None:
                self._errors['registration_ends'] = self.error_class(
                    ['Avslutningstidspunkt for påmelding må spesifiseres for påmeldingsarrangement'])
            if self.cleaned_data.get('max_attendees') < 1:
                self._errors['max_attendees'] = self.error_class(
                    ['Maks deltagere må være større enn 0'])
            if registration_ends is not None and registration_starts is not None:
                if registration_starts > registration_ends:
                    self._errors['registration_ends'] = self.error_class(
                        ['Avslutningstidspunkt for påmelding må være etter starttidspunkt for påmelding'])
        else:
            self.cleaned_data['max_attendees'] = 0

        if self.cleaned_data.get('business_presentation'):
            if self.cleaned_data.get('company') is None:
                self._errors['company'] = self.error_class(
                    ['Bedrift må velges for bedriftspresentasjon'])

        return self.cleaned_data

    class Meta:
        model = Event
        fields = [
            'title',
            'description',
            'start_time',
            'end_time',
            'registration',
            'registration_starts',
            'registration_ends',
            'max_attendees',
            'location',
            'organizer',
            'invited_years',
            'business_presentation',
            'company',
            'special_event',
            'binding_registration',
        ]

        labels = {
            'title': ('Tittel'),
            'description': ('Beskrivelse'),
            'start_time': ('Starttidspunkt'),
            'end_time': ('Slutttidspunkt'),
            'registration': ('Påmeldingsarrangement?'),
            'registration_starts': ('Påmelding starter'),
            'registration_ends': ('Påmelding slutter'),
            'max_attendees': ('Maks deltagere'),
            'location': ('Sted'),
            'organizer': ('Arrangør'),
            'invited_years': ('Inviterte'),
            'business_presentation': ('Bedriftspresentasjon'),
            'company': ('Bedrift'),
            'binding_registration': ('Bindende påmelding'),
        }

        help_texts = {
            'binding_registration': 'Kun for betalende arrangementer',
        }

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        EventConfig.get_solo()
        special_event = EventConfig.objects.values()
        if True in list(special_event[0].values())[1:]:
            return
        else:
            del self.fields['special_event']

events/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
import datetime
import csv
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.utils.safestring import mark_safe
from django.core.exceptions import PermissionDenied

from django.core.mail import send_mail
from django.template.loader import render_to_string
from mannhulletweb2.settings import base
from .forms import EventForm
from .models import Event, Attendance
from users.models import Mannhullitt
from .utils import Calendar


def send_waiting_list_email(user, event):
    # Create message container - the correct MIME type is multipart/alternative.
    sender = base.EMAIL_HOST_USER
    reciever = user.email

    url = f"mannhullet.no{reverse('events:event_details', args=(event.pk,))}"

    # Create the body of the message (a plain-text and an HTML version).
    text = f"""
        Hei {user.get_full_name()}!\n
        Du har nå fått plass på {event.title}!
        Dersom du ikke har mulighet til å delta, meld deg av på mannhullet.no
    """
    html = f'''
    <div style="font-size: 16px">
        <p>Hei {user.get_full_name()}!<br><br>
        Du har nå fått plass på {event.title}<br>
        Dersom du ikke har mulighet til å delta,
        meld deg av på <link href={url}>{url}<link>.
        </p>
    </div>
    '''

    send_mail(
        subject=f"Du har blitt tildelt plass på {event.title}",
        message=text,
        html_message=render_to_string('email_base.html', {'contents': html}),
        recipient_list=[reciever, ],
        from_email=sender,
        fail_silently=False,
    )


def send_registered_dot_email(user, event):
    # Create message container - the correct MIME type is multipart/alternative.
    sender = base.EMAIL_HOST_USER
    reciever = user.email
    dots = user.dots

    # Create the body of the message (a plain-text and an HTML version).
    text = f'''
        Hei {user.get_full_name()}!\n
        Du har fått en prikk fra følgene arrangement: {event.title}, og har nå {dots} prikk(er).
        Dersom du mener dette er feil kan du ta kontakt med bedriftskontakt@marin.ntnu.no
    '''
    html = f'''
    <div style="font-size: 16px">
        <p>Hei {user.get_full_name()}!<br><br>
        Du har fått en prikk fra følgende arrangement: {event.title}, og har nå {dots} prikk(er).<br>
        Dersom du mener dette er feil kan du ta kontakt med bedriftskontakt@marin.ntnu.no.
        </p>
    </div>
    '''

    send_mail(
        subject=f"Prikk tildelt grunnet {event.title}",
        message=text,
        html_message=render_to_string('email_base.html', {'contents': html}),
        recipient_list=[reciever, ],
        from_email=sender,
        fail_silently=False,
    )


def get_all_event_attendees(event):
    # Attendance objects are sorted by timestamp. This means
    # We have to get the Attendence objects first, and then
    # find the connected users through this.
    attendances = Attendance.objects.filter(event=event)
    return [attendance.attendee for attendance in attendances]


def has_event_permisson(user):  # Used to check if user is in correct group
    permitted_groups = ['Styret', 'Bedriftskontakt', 'Undergruppeadmin', 'Webgruppen']
    if user.is_superuser:
        return True
    else:
        for group in permitted_groups:
            if user.groups.filter(name=group).exists():
                return True
        return False


def events(request):
    events_list = Event.objects.filter(end_time__gte=timezone.now()).order_by('end_time')
    return render(request, 'events/events.html', {'events_list': events_list})


def create_event(request):
    form = EventForm
    user = request.user
    if has_event_permisson(user):
        if request.method == 'POST':
            form = EventForm(data=request.POST)
            if form.is_valid():
                form.save()
                event = Event.objects.latest('pk')
                pk = event.pk
                return HttpResponseRedirect(reverse('events:event_details', args=(pk,)))
            else:
                return render(request, 'events/create_event.html', {'form': form})
        return render(request, 'events/create_event.html', {'form': form})
    else:
        raise PermissionDenied


def change_event(request, pk):
    event = get_object_or_404(Event, pk=pk)
    attendees = Attendance.objects.filter(event=event)[:event.max_attendees]
    form = EventForm(instance=event)
    already_invited = []
    already_invited[:0] = event.invited_years
    form.initial['invited_years'] = already_invited
    user = request.user
    event_finished = bool(timezone.now() > event.end_time)
    context = {'form': form, 'event': event, "attendees": attendees, "event_finished": event_finished}
    if has_event_permisson(user):
        if request.method == 'POST':
            form = EventForm(data=request.POST, instance=event)
            if form.is_valid():
                if "submit" in request.POST:
                    form.save()
                    event.save()
                    return HttpResponseRedirect(reverse('events:event_details', args=(pk,)))
            else:
                context['form'] = form
                return render(request, 'events/change_event.html', context)
        return render(request, 'events/change_event.html', context)
    else:
        raise PermissionDenied


def event_details(request, pk):
    event = get_object_or_404(Event, pk=pk)
    user = request.user
    registered = get_all_event_attendees(event=event)
    attendees = registered[:event.max_attendees]
    waiting = registered[event.max_attendees:]
    if waiting:
        can_sign_off = event.start_time - datetime.timedelta(hours=8) > timezone.now()
    else:
        can_sign_off = event.start_time - datetime.timedelta(hours=8) > timezone.now() \
                       and not event.binding_registration

    context = {}
    if request.method == 'POST':
        if "attending" in request.POST:
            if event.business_presentation and user.dots >= 3:
                raise Http404
            event.attendees.add(user)
            return HttpResponseRedirect(reverse('events:event_details', args=(pk,)))
        elif "not_attending" in request.POST:

            # Checks if current time is past 12:00 day before start of event, and if so give dot
            start_time = event.start_time.time()
            late_register_time = event.start_time - datetime.timedelta(days=1) - \
                datetime.timedelta(hours=start_time.hour, minutes=start_time.minute) + datetime.timedelta(hours=12)

            if (late_register_time < timezone.now() and user in attendees and event.business_presentation):
                register_user_dot(event=event, email=user.email)

            # Checks if there are users on the waiting list
            if len(waiting) > 0 and user in attendees:
                send_waiting_list_email(event=event, user=waiting[0])

            event.attendees.remove(user)
            return HttpResponseRedirect(reverse('events:event_details', args=(pk,)))
    context = {'event': event, 'attendees': attendees, 'user': user, 'waiting': waiting, 'can_sign_off': can_sign_off}
    if event.registration:
        context['open'] = bool(event.registration_starts < timezone.now() < event.registration_ends)
        context['closed'] = bool(timezone.now() > event.registration_ends)
    return render(request, 'events/event_details.html', context)


def register_attendance(request, pk, email):
    event = get_object_or_404(Event, pk=pk)
    attendee = get_object_or_404(Mannhullitt, email=email)
    user = request.user
    if has_event_permisson(user):
        if request.method == 'POST':
            attendance = Attendance.objects.filter(event=event, attendee=attendee)[0]
            attendance.has_attended = True
            attendance.save()
            return HttpResponseRedirect(reverse('events:change_event', args=(pk,)))
        else:
            raise Http404
    else:
        raise PermissionDenied


def remove_attendance(request, pk, email):
    event = get_object_or_404(Event, pk=pk)
    attendee = get_object_or_404(Mannhullitt, email=email)
    user = request.user
    if has_event_permisson(user):
        if request.method == 'POST':
            attendance = Attendance.objects.filter(event=event, attendee=attendee)[0]
            attendance.has_attended = False
            attendance.save()
            return HttpResponseRedirect(reverse('events:change_event', args=(pk,)))
        else:
            raise Http404
    else:
        raise PermissionDenied


def register_user_dot(event, email):
    attendee = get_object_or_404(Mannhullitt, email=email)
    attendance = Attendance.objects.filter(event=event, attendee=attendee)[0]
    attendance.recieved_dot = True
    attendance.save()
    attendee.register_dot()
    send_registered_dot_email(event=event, user=attendee)


def register_dots(request, pk, email):
    event = get_object_or_404(Event, pk=pk)
    user = request.user
    if has_event_permisson(user):
        if request.method == 'POST':
            register_user_dot(event=event, email=email)
            return HttpResponseRedirect(reverse('events:change_event', args=(pk,)))
        else:
            raise Http404
    else:
        raise PermissionDenied


def delete_event(request, pk):
    if request.method == 'POST':
        user = request.user
        if has_event_permisson(user):
            event = get_object_or_404(Event, pk=pk)
            event.delete()
            return HttpResponseRedirect(reverse('events:events'))
        else:
            raise PermissionDenied
    else:
        raise Http404


def calendar_view(request, year=None, month=None):
    if year is None:
        year = timezone.now().year
    if month is None:
        month = timezone.now().month

    events_list = Event.objects.filter(start_time__gte=timezone.now()).order_by('start_time')

templates/events/change_event.html
{% extends './event_base.html' %}
{% load static %}

{% load static %}

{% block title %}Endre arrangement{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-10 col-md-6">
      <h3> Endre arrangement </h3>
      <form method="post">
        {% csrf_token %}
        {% for field in form %}
          <h3>{{ field.label_tag }}</h3>
          <p class="evnt-helptext">{{field.help_text}}</p>
          <p>{{ field }}</p>
          <div class="form-errors">
            <p>{{field.errors}}</p>
          </div>
        {% endfor %}

        <button class="btn btn-default event-btn" name="submit">
        Lagre</button>
      </form>

      <form action="{% url 'events:delete_event' event.pk %}" method="post">
        {% csrf_token %}
         <div class="modal fade" id="deleteEventModal" tabindex="-1" role="dialog" aria-labelledby="deleteEventModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="deleteEventModalLabel">Slett arrangement</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                Sikker på at du vil slette arrangementet {{event.title}}?
              </div>
              <div class="modal-footer">
                <div class="col-sm-6">
                  <button class="modal-close-btn btn btn-default modal-event-btn">Lukk</button>
                </div>
                <div class="col-sm-6">
                  <button class="btn btn-danger modal-event-btn">Slett arrangement</button>
                </div>
              </div>
            </div>
          </div>
        </div>

        <button type="button" class="btn btn-danger event-btn event-delete-btn" data-toggle="modal" data-target="#deleteEventModal">
          Slett arrangement
        </button>
      </form>

    </div>
    <div class="col-sm-10 col-md-6">
      <div class="row">
        <div class="col-sm-6 col-md-4" style="margin-bottom: 15px;">
          <form action="{% url 'events:export_attendees' event.pk %}" method="post">
            {% csrf_token %}
            <button class="btn btn-default">
              Eksporter deltagere
            </button>
          </form>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12 col-md-6">
          <h3>
            Deltagere
          </h3>
          {% for attendance in attendees %}
            {% if not attendance.has_attended %}
                <div class="row">
                  <div class="col-sm-10 col-md-8">
                    <p>{{ attendance.attendee.first_name }} {{attendance.attendee.last_name}}</p>
                  </div>
                  <div class="col-sm-2 col-md-4">
                    {% if not event_finished %}
                    <form action="{% url 'events:register_attendance' event.pk attendance.attendee.email %}" method="post">
                      {% csrf_token %}
                      <button class="btn btn-default">
                        Reg
                      </button>
                    </form>
                    {% elif not attendance.recieved_dot %}
                      <form action="{% url 'events:register_dots' event.pk attendance.attendee.email %}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-default">
                          Prikk
                        </button>
                      </form>
                    {% endif %}
                  </div>
                </div>
            {% endif %}
          {% endfor %}
        </div>
        <div class="col-sm-12 col-md-6">
          <h3>
            Møtt opp
          </h3>
          {% for attendance in attendees %}
            {% if attendance.has_attended %}
              <div class="row">
                <div class="col-sm-10 col-md-8">
                  <p>{{ attendance.attendee.first_name }} {{attendance.attendee.last_name}}</p>
                </div>
                {% if not event_finished %}
                <form action="{% url 'events:remove_attendance' event.pk attendance.attendee.email %}" method="post">
                  {% csrf_token %}
                  <button class="btn btn-default">
                    UnReg
                  </button>
                </form>
              </div>
              {% endif %}
          {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
</div>
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugin/tinymce/tinymce.min.js' %}" ></script>
<script type="text/javascript" src= "{% static 'plugin/tinymce/init-tinymce.js' %}"></script>
<script type="text/javascript" src="/jsi18n/"></script>
<script type="text/javascript" src={% static "/admin/js/core.js" %}></script>
<script type="text/javascript" src={% static "/admin/js/admin/RelatedObjectLookups.js" %}></script>
<script type="text/javascript" src={% static "/admin/js/calendar.js" %}></script>
<script type="text/javascript" src={% static "/admin/js/admin/DateTimeShortcuts.js" %}></script>
<script type="text/javascript" src={% static "admin/js/vendor/jquery/jquery.js" %}></script>
<script type="text/javascript" src={% static "admin/js/jquery.init.js" %}></script>
<link rel="stylesheet" type="text/css" href={% static "admin/css/widgets.css" %} />

{% endblock %}

templates/events/create_event.html
{% extends './event_base.html' %}
{% load static %}

{% load static %}

{% block title %}Opprett arrangement{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-offset-0 col-sm-8 col-md-offset-1 col-md-6">
      <div class="overskrift">
        <h1> Opprett arrangement </h1>
      </div>
      <form method="post">
        {% csrf_token %}
        {% for field in form %}
          <h3>{{ field.label_tag }}</h3>
          <p class="evnt-helptext">{{field.help_text}}</p>
          <p>{{ field }}</p>
          <div class="form-errors">
            <p>{{field.errors}}</p>
          </div>
        {% endfor %}

        <button class="btn btn-default event-btn" name="submit">
          Lagre
        </button>
      </form>
    </div>
  </div>
</div>
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugin/tinymce/tinymce.min.js' %}" ></script>
<script type="text/javascript" src= "{% static 'plugin/tinymce/init-tinymce.js' %}"></script>
<script type="text/javascript" src="/jsi18n/"></script>
<script type="text/javascript" src={% static "/admin/js/core.js" %}></script>
<script type="text/javascript" src={% static "/admin/js/admin/RelatedObjectLookups.js" %}></script>
<script type="text/javascript" src={% static "/admin/js/calendar.js" %}></script>
<script type="text/javascript" src={% static "/admin/js/admin/DateTimeShortcuts.js" %}></script>
<script type="text/javascript" src={% static "admin/js/vendor/jquery/jquery.js" %}></script>
<script type="text/javascript" src={% static "admin/js/jquery.init.js" %}></script>
<link rel="stylesheet" type="text/css" href={% static "admin/css/widgets.css" %} />
{% endblock %}

templates/events/event_base.html
{% extends 'base.html' %}
{% load static %}

{% block app_css %}<link rel="stylesheet" href={% static "events/css/event.css" %}>{% endblock %}

templates/events/event_calendar.html
{% extends './event_base.html' %}
{% load static %}
{% load template_tags %}
{% block title %}Kalender{% endblock %}

{% block additional_styles %}
  <style>
    body {
      background-color: #FFFFFF;
    }
  </style>
{% endblock %}

{% block content %}
<div class="wrap" style="margin-left: -1em">
  <div class="content">
    <div class="container">
        <div class="calendar clearfix">
          <div class="row calender-top-section">
            <div class="col-1 justify-content-center">
              <a href={% url 'events:calendar_month' year=prev_year month=prev_month %} class="month-arrow-left">
                <i class="fa fa-angle-double-left arrow-left"></i>
              </a>
            </div>
            <div id="calendar-title" class="col-10 calendar-title">
              Arrangementer for {{month}}
            </div>
            <div class="col-1 justify-content-center">
              <a href={% url 'events:calendar_month' year=next_year month=next_month %} class="month-arrow-right">
                <i class="fa fa-angle-double-right arrow-right"></i></a>
            </div>
          </div>
          <div class="row">
              <div class="col-sm-12">
                <div class="pull-left toggle-calendar">
                  {% if request.user|has_event_permisson %}
                    <a href="{% url 'events:create_event'%}" class="btn-color-dark"> <i class="fa fa-plus mr-2"></i>Nytt arrangement</a>
                  {% endif %}
                </div>
              </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <div class="pull-left toggle-calendar">
                  <a><i class='fa fa-circle' style='color: #404d75'></i> Mannhullet</a>
              </div>
              <div class="pull-left toggle-calendar">
                    <a><i class='fa fa-circle' style='color: #6A80C5'></i> Bedriftpresentasjon</a>
              </div>
              {% if special_events.RUKA %}
                 <div class="pull-left toggle-calendar">
                      <a><i class='fa fa-circle' style='color: #bc1423'></i> RUKA</a>
                 </div>
              {% endif %}

               {% if special_events.Bedriftsdagen %}
                 <div class="pull-left toggle-calendar">
                      <a><i class='fa fa-circle' style='color: #00a7e6'></i> Bedriftsdagen</a>
                 </div>
              {% endif %}

               {% if special_events.Jubileum %}
                 <div class="pull-left toggle-calendar">
                      <a><i class='fa fa-circle' style='color: #C9AE5D'></i> Jubileum</a>
                 </div>
              {% endif %}

              <div class="pull-right toggle-calendar">
                <a  href="{% url 'events:events' %}" class="btn-color-dark"><i class="fa fa-list"></i></a>
              </div>
            </div>
          </div>
          <div>
            <div class="table-responsive" style="overflow-y: auto;">
              <table class="table table-bordered table-hover table-calendar">
                <thead>
                  <tr>
                    <th id="week">Uke</th>
                    <th class="weekday">Mandag</th>
                    <th class="weekday">Tirsdag</th>
                    <th class="weekday">Onsdag</th>
                    <th class="weekday">Torsdag</th>
                    <th class="weekday">Fredag</th>
                    <th class="weekday">Lørdag</th>
                    <th class="weekday">Søndag</th>
                  </tr>
                </thead>
                {{calendar}}
              </table>
           </div>
          </div>
        </div>
      </div>
  </div>
</div>

<script>
  if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
    console.log("{% url 'events:events' %}")
    window.location.replace("{% url 'events:events' %}")

    //month = "{{month}}"
    //document.getElementById('calendar-title').innerHTML = month.charAt(0).toUpperCase() + month.slice(1);
  }
</script>
{% endblock %}